apiVersion: v1
kind: Service
metadata:
  name: store-ui
spec:
  selector:
    app: store-ui
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-ui
  template:
    metadata:
      labels:
        app: store-ui
    spec:
      containers:
        - name: store-ui
          image: store-ui:latest
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent