apiVersion: v1
kind: Service
metadata:
  name: store-shopping-service
spec:
  selector:
    app: store-shopping-service
  ports:
    - port: 9091
      targetPort: 9091

  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-shopping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-shopping-service
  template:
    metadata:
      labels:
        app: store-shopping-service
    spec:
      containers:
        - name: store-shopping-service
          image: store-shopping:latest
          ports:
            - containerPort: 9091
          env:
            - name: KAFKA_SERVER
              value: kafka-service:9093
          imagePullPolicy: IfNotPresent