apiVersion: v1
kind: Service
metadata:
  name: store-creditcard-service
spec:
  selector:
    app: store-creditcard-service
  ports:
    - port: 9092
      targetPort: 9092
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-creditcard-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-creditcard-service
  template:
    metadata:
      labels:
        app: store-creditcard-service
    spec:
      containers:
        - name: store-creditcard-service
          image: store-creditcard:latest
          ports:
            - containerPort: 9092
          imagePullPolicy: IfNotPresent